//aws_access_key = ""
//aws_secret_key = ""
myami = "ami-0f095f89ae15be883"
mykey = "oliver"
mykeypem = "oliver.pem"
tags = ["control_node", "db_server", "web_server"]
instancetype = "t2.micro"
num = 3
region = "us-east-1"
mysecgr = "ansible-session4-sec-gr"
